[package]
name = "code-royale"
version = "0.1.0"
edition = "2018"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"


[build-dependencies]
rustsourcebundler = "0.11.0"
